version: '3'
services:
  gcloud:
    build: ./containers/gcloud
    tty: true
    volumes:
      - ./src:/src:cached

  app:
    build: ./containers/golang
    volumes:
      - ./src/app:/go/src/app
    ports:
      - "80:8080"
    environment:
      - "GOPATH=/go"
    tty: true